Repository bratislava/marianum.sk, pull requests merged in 2023-05, with the labels that each got.

#295 remove Sentry related code
  next/README.md
  next/next.config.js
  next/package.json
  next/pages/_error.tsx
  next/pages/api/revalidate.ts
  next/pages/sentry-test.tsx
  next/sentry.client.config.js
  next/sentry.properties
  next/sentry.server.config.js
  next/yarn.lock
Labels: needs review :pray:

#288 feat: added labels to .github/workflow jobs to run on self-hosted
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  next/.dockerignore
  next/Dockerfile
  next/kubernetes/base/ingress.yml
  next/next.config.js
  next/yarn.lock
  strapi/.dockerignore
  strapi/Dockerfile
  strapi/kubernetes/base/ingress.yml
  strapi/package.json
Labels: infrastructure

#302 Update Strapi and fix errors
  strapi/package.json
  strapi/src/api/application/services/application.ts
  strapi/src/plugins/ceremonies-debtor-list/admin/src/index.tsx
  strapi/src/plugins/ceremonies-debtor-list/admin/src/utils/axiosInstance.ts
  strapi/src/plugins/ceremonies-debtor-list/package.json
  strapi/src/plugins/ceremonies-debtor-list/yarn.lock
  strapi/yarn.lock
Labels: fix & ship :ship:
