Repository bratislava/marianum.sk, pull requests merged in 2023-02, with the labels that each got.

#276 Increase timeout
  strapi/src/plugins/ceremonies-debtor-list/server/controllers/index.ts
Labels: needs review :pray:

#278 increase maxTotalHits for debtors
  strapi/config/plugins.ts
Labels: fix & ship :ship:

#281 Listings improvements
  next/.env
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/Dockerfile
  next/components/atoms/RichText.tsx
  next/components/atoms/Seo.tsx
  next/components/molecules/CeremoniesDebtors/CemeterySelect.tsx
  next/components/sections/CeremoniesArchiveSection.tsx
  next/components/sections/CeremoniesSection.tsx
  next/components/sections/DebtorsSection.tsx
  next/components/sections/DisclosuresSection.tsx
  next/pages/articles/[...fullPath].tsx
  next/pages/branches/[...fullPath].tsx
  next/pages/bundles/[...fullPath].tsx
  next/pages/cemeteries/[...fullPath].tsx
  next/pages/documents/[...fullPath].tsx
  next/pages/index.tsx
  next/pages/pages/[...fullPath].tsx
  next/services/fetchers/ceremoniesArchiveSectionFetcher.ts
  next/services/fetchers/ceremoniesSectionFetcher.ts
  next/services/fetchers/debtorsSectionFetcher.ts
  next/services/fetchers/disclosuresSectionFetcher.ts
  next/styles/table.scss
  next/utils/useHorizontalScrollFade.ts
  strapi/Dockerfile
Labels: needs review :pray:

#283 fix: fix/slim up Strapi Dockerfile
  strapi/.dockerignore
  strapi/Dockerfile
  strapi/package.json
Labels: infrastructure
