Repository bratislava/marianum.sk, pull requests merged in 2023-01, with the labels that each got.

#246 Fix transforming entry
  strapi/config/plugins.ts
Labels: needs review :pray:

#253 replace footer map by static mapbox image
  next/components/atoms/Breadcrumbs.tsx
  next/components/molecules/Footer/Footer.tsx
  next/components/molecules/Footer/FooterMapStatic.tsx
  next/graphql/index.ts
  next/graphql/queries/components.gql
  next/next.config.js
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  strapi/src/components/general/contacts.json
Labels: fix & ship :ship:

#272 feat: Added variables to requests resources CPU/Mem
  next/kubernetes/base/deployment.yml
  next/kubernetes/envs/Dev/config.json
  next/kubernetes/envs/Prod/config.json
  next/kubernetes/envs/Staging/config.json
  strapi/kubernetes/base/deployment.yml
  strapi/kubernetes/base/stateful-set-meilisearch.yml
  strapi/kubernetes/base/stateful-set.yml
  strapi/kubernetes/envs/Dev/config.json
  strapi/kubernetes/envs/Prod/config.json
  strapi/kubernetes/envs/Staging/config.json
Labels: infrastructure
