Repository bratislava/marianum.sk, pull requests merged in 2025-03, with the labels that each got.

#492 #331 Implement NOT_FOUND with revalidate property
  next/components/molecules/Navigation/NavigationProvider/generateStaticPathsAndProps.ts
  next/pages/index.tsx
  next/utils/consts.ts
Labels: pr: fix & ship :ship:

#498 #389 Add gallery to cemetery detail page
  next/graphql/index.ts
  next/graphql/queries/components.gql
  next/graphql/queries/entities.gql
  next/pages/cemeteries/[...fullPath].tsx
  next/public/locales/sk/common.json
  strapi/schema.graphql
  strapi/src/api/cemetery/content-types/cemetery/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#503 Use title from Strapi in Gallery
  next/pages/cemeteries/[...fullPath].tsx
Labels: pr: fix & ship :ship:

#500 #469 upgrade graphql, markdown, typescript and clean unused dependencies
  next/codegen.ts
  next/codegen.yml
  next/components/atoms/RichText.tsx
  next/graphql/index.ts
  next/next.config.js
  next/package.json
  next/yarn.lock
  strapi/schema.graphql
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#506 #488 Fix broken URLs for detail pages of managed objects
  next/next.config.js
Labels: pr: fix & ship :ship:

#501 #372 Enhance accessibility and structure of Accordion components
  next/components/molecules/Accordion/AccordionItem.tsx
  next/styles/globals.css
Labels: pr: fix & ship :ship:

#499 #494 Documents subsection to cemeteries
  marianum.code-workspace
  next/components/molecules/DocumentGroup.tsx
  next/components/molecules/Row/DocumentRow.tsx
  next/components/molecules/Row/Row.tsx
  next/components/molecules/SectionBoxed.tsx
  next/graphql/index.ts
  next/graphql/queries/entities.gql
  next/pages/cemeteries/[...fullPath].tsx
  strapi/schema.graphql
  strapi/src/api/cemetery/content-types/cemetery/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#516 Fix graphql index.ts
  next/graphql/index.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#507 #390 add option to add video in cemeteries detail page
  next/components/sections/IframeSection.tsx
  next/graphql/index.ts
  next/graphql/queries/entities.gql
  next/pages/cemeteries/[...fullPath].tsx
  next/public/locales/sk/translation.json
  strapi/schema.graphql
  strapi/src/api/cemetery/content-types/cemetery/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#524 #522 BugFix ServiceCards in CardSection
  next/components/molecules/Cards/ServiceCard.tsx
  next/components/sections/CardSection.tsx
Labels: pr: fix & ship :ship:

#504 #372 Create SelectField using react-select
  next/components/atoms/SelectField.tsx
  next/package.json
  next/pages/styleguide.tsx
  next/yarn.lock
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#532 #505 Remove legacy "Application" content type
  next/graphql/index.ts
  strapi/schema.graphql
  strapi/src/api/application/content-types/application/schema.json
  strapi/src/api/application/controllers/application.ts
  strapi/src/api/application/routes/application.ts
  strapi/src/api/application/services/application.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#535 #494 Fix for video location in cemeteries
  next/pages/cemeteries/[...fullPath].tsx
Labels: pr: fix & ship :ship:

#539 #493 quickfix gallery counter
  next/components/molecules/ImageGallery.tsx
Labels: pr: fix & ship :ship:

#542 Show only current year in footer copyright
  next/components/molecules/Footer/FooterCredentials.tsx
Labels: pr: fix & ship :ship:

#527 #364 Add focus rings to input-like components, gallery, and slider
  next/components/atoms/TextField.tsx
  next/components/molecules/Accordion/AccordionItem.tsx
  next/components/molecules/ImageGallery.tsx
  next/components/molecules/Slider.tsx
  next/components/sections/HomepageSlider.tsx
  next/pages/search.tsx
  next/pages/styleguide.tsx
Labels: pr: fix & ship :ship:

#546 Fix for Iframe section
  next/components/sections/IframeSection.tsx
Labels: pr: fix & ship :ship:

#520 #441 techdebt rewrite swr to tanstackreact query - part 1
  next/.eslintrc.js
  next/components/atoms/LoadingOverlay.tsx
  next/components/molecules/CeremoniesDebtors/CemeterySelect.tsx
  next/components/molecules/Navigation/NavigationSearch/NavigationSearch.tsx
  next/components/molecules/ProcedureTabs.tsx
  next/components/molecules/SelectWithFetcher.tsx
  next/components/providers/BAQueryClientProvider.tsx
  next/components/providers/MI18nProvider.tsx
  next/components/sections/ArticleListing/ArticleJobsCategoriesSelect.tsx
  next/components/sections/ArticleListing/ArticleListing.tsx
  next/components/sections/ArticleListing/ArticleNewsCategoriesSelect.tsx
  next/components/sections/ArticleListing/ArticlePressCategoriesSelect.tsx
  next/components/sections/CeremoniesArchiveSection.tsx
  next/components/sections/CeremoniesSection.tsx
  next/components/sections/DebtorsSection.tsx
  next/components/sections/DisclosuresSection.tsx
  next/components/sections/DocumentsSection/DocumentsSection.tsx
  next/components/sections/DocumentsSection/DocumentsSectionCategorySelect.tsx
  next/components/sections/DocumentsSection/DocumentsSectionFiletypeSelect.tsx
  next/components/sections/MapOfManagedObjectsSection.tsx
  next/components/sections/MapSection.tsx
  next/components/sections/NewsListing.tsx
  next/components/sections/PartnersSection.tsx
  next/components/sections/UpcomingCeremoniesSection.tsx
  next/graphql/index.ts
  next/graphql/queries/components.gql
  next/graphql/queries/entities.gql
  next/package.json
  next/pages/_app.tsx
  next/pages/pages/[...fullPath].tsx
  next/pages/search.tsx
  next/public/locales/sk/translation.json
  next/services/fetchers/articleListingFetcher.ts
  next/services/fetchers/cemeteriesFetcher.ts
  next/services/fetchers/ceremoniesArchiveSectionFetcher.ts
  next/services/fetchers/ceremoniesSectionFetcher.ts
  next/services/fetchers/debtorsSectionFetcher.ts
  next/services/fetchers/disclosuresSectionFetcher.ts
  next/services/fetchers/documentsSectionFetcher.ts
  next/services/fetchers/managedObjectsFetcher.ts
  next/services/fetchers/newsListingFetcher.ts
  next/services/fetchers/partnersSectionFetcher.ts
  next/services/fetchers/proceduresFetcher.ts
  next/services/fetchers/upcomingCeremoniesFetcher.ts
  next/utils/useSearch.ts
  next/yarn.lock
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/partners-section.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#525 #364 Focus rings refactoring: Cards, rows, lines, tabs, and other row-like components
  next/components/atoms/Card/CardBox.tsx
  next/components/atoms/Row/RowBox.tsx
  next/components/atoms/Tabs/TabLabel.tsx
  next/components/atoms/Tabs/TabPanel.tsx
  next/components/atoms/Tabs/Tabs.tsx
  next/components/molecules/Checklist/Checklist.tsx
  next/components/molecules/Row/DocumentRow.tsx
  next/components/molecules/Section.tsx
  next/components/sections/ArticleGroup.tsx
  next/components/sections/CeremoniesSection.tsx
  next/components/sections/DocumentsSection/DocumentsSection.tsx
  next/components/sections/MapOfManagedObjectsSection.tsx
  next/components/sections/MapSection.tsx
Labels: pr: fix & ship :ship:

#548 #517 techdebt upgrade dependabot suggestions
  next/components/atoms/Modal.tsx
  next/package.json
  next/yarn.lock
  strapi/package.json
  strapi/patches/strapi-plugin-navigation+2.3.1.patch
  strapi/src/plugins/ceremonies-debtor-list/yarn.lock
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#523 #508 add link component to homepage
  next/components/molecules/CtaGroup.tsx
  next/components/molecules/Footer/FooterCredentials.tsx
  next/components/molecules/Navigation/NavigationProvider/useGetLinkProps.ts
  next/components/molecules/Section.tsx
  next/components/molecules/SideBar.tsx
  next/components/sections/CeremoniesSection.tsx
  next/components/sections/HeroSection.tsx
  next/components/sections/HomepageProceduresSection.tsx
  next/components/sections/HomepageSlider.tsx
  next/components/sections/RichTextSection.tsx
  next/components/sections/UpcomingCeremoniesSection.tsx
  next/graphql/index.ts
  next/graphql/queries/components.gql
  next/graphql/queries/entities.gql
  strapi/schema.graphql
  strapi/src/components/blocks/button-link.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#559 Rename managed_objects to managedObjects
  next/components/molecules/Navigation/NavigationProvider/useGetLinkProps.ts
  next/graphql/index.ts
  next/graphql/queries/components.gql
  strapi/schema.graphql
  strapi/src/components/blocks/button-link.json
  strapi/types/generated/components.d.ts
Labels: pr: needs review :pray:

#560 Implement react-query prefetching for cemeteries only to fix cemetery map
  next/pages/pages/[...fullPath].tsx
  next/utils/prefetchPageSections.ts
Labels: pr: fix & ship :ship:

#558 #489 Add Bootstrapped Revalidate Webhook setup
  .gitignore
  next/.env.example
  next/kubernetes/base/deployment.yml
  next/kubernetes/base/secrets/general.secret.dev.yml
  next/kubernetes/base/secrets/general.secret.prod.yml
  next/kubernetes/base/secrets/general.secret.staging.yml
  next/kubernetes/base/secrets/general.yml
  next/kubernetes/envs/Dev/kustomization.yml
  next/kubernetes/envs/Dev/secrets/cloudflare-turnstile.secret.yml
  next/kubernetes/envs/Prod/kustomization.yml
  next/kubernetes/envs/Prod/secrets/cloudflare-turnstile.secret.yml
  next/kubernetes/envs/Staging/kustomization.yml
  next/kubernetes/envs/Staging/secrets/cloudflare-turnstile.secret.yml
  next/pages/api/revalidate.ts
  src/api/your-entity/content-types/your-entity/lifecycles.js
  strapi/.env.example
  strapi/kubernetes/base/deployment.yml
  strapi/kubernetes/envs/Dev/.env
  strapi/kubernetes/envs/Dev/kustomization.yml
  strapi/kubernetes/envs/Dev/secrets/generics.secret.yml
  strapi/kubernetes/envs/Prod/.env
  strapi/kubernetes/envs/Prod/kustomization.yml
  strapi/kubernetes/envs/Prod/secrets/generics.secret.yml
  strapi/kubernetes/envs/Staging/.env
  strapi/kubernetes/envs/Staging/kustomization.yml
  strapi/kubernetes/envs/Staging/secrets/generics.secret.yml
  strapi/src/index.ts
Labels: pr: fix & ship :ship:

#561 547 techdebt rewrite swr to tanstackreact query part 2
  next/components/molecules/CeremoniesDebtors/CemeterySelect.tsx
  next/components/sections/ArticleListing/ArticleJobsCategoriesSelect.tsx
  next/components/sections/ArticleListing/ArticleListing.tsx
  next/components/sections/ArticleListing/ArticleNewsCategoriesSelect.tsx
  next/components/sections/ArticleListing/ArticlePressCategoriesSelect.tsx
  next/components/sections/CeremoniesArchiveSection.tsx
  next/components/sections/CeremoniesSection.tsx
  next/components/sections/DebtorsSection.tsx
  next/components/sections/DisclosuresSection.tsx
  next/components/sections/DocumentsSection/DocumentsSection.tsx
  next/components/sections/MapSection.tsx
  next/components/sections/NewsListing.tsx
  next/components/sections/ReviewListingSection.tsx
  next/components/sections/UpcomingCeremoniesSection.tsx
  next/package.json
  next/pages/index.tsx
  next/pages/pages/[...fullPath].tsx
  next/services/fetchers/articleListingFetcher.ts
  next/services/fetchers/articles/articleCategoriesSelectFetcher.ts
  next/services/fetchers/articles/articlesFetcher.ts
  next/services/fetchers/articles/newsListingFetcher.ts
  next/services/fetchers/cemeteries/cemeteriesFetcher.ts
  next/services/fetchers/cemeteries/cemeteriesInCeremoniesFetcher.ts
  next/services/fetchers/cemeteries/cemeteriesInDebtorsFetcher.ts
  next/services/fetchers/ceremonies/ceremoniesArchiveSectionFetcher.ts
  next/services/fetchers/ceremonies/ceremoniesSectionFetcher.ts
  next/services/fetchers/ceremonies/upcomingCeremoniesFetcher.ts
  next/services/fetchers/ceremoniesSectionFetcher.ts
  next/services/fetchers/debtorsFetcher.ts
  next/services/fetchers/debtorsSectionFetcher.ts
  next/services/fetchers/disclosuresFetcher.ts
  next/services/fetchers/documentsFetcher.ts
  next/services/fetchers/managedObjectsFetcher.ts
  next/services/fetchers/newsListingFetcher.ts
  next/services/fetchers/proceduresFetcher.ts
  next/services/fetchers/reviewsFetcher.ts
  next/utils/prefetchPageSections.ts
  next/utils/prefetchSections.ts
  next/utils/useGetSwrExtras.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:
