Repository bratislava/marianum.sk, pull requests merged in 2025-02, with the labels that each got.

#417 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr: needs review :pray:

#415 Add missing .env setup
  next/.env.development
  next/.env.example
  next/.env.production
  next/.eslintrc.js
  strapi/.env.example
  strapi/config/database.ts
Labels: pr: fix & ship :ship:

#428 Add PR Labeler workflow
  .github/workflows/label.yml
Labels: pr: fix & ship :ship:

#430 #429 Setup postgres volume in docker-compose
  .gitignore
  docker-compose.yml
Labels: pr: fix & ship :ship:

#433 #432 upgrade next to v14 and typescript to v5
  next/Dockerfile
  next/components/atoms/AnimateHeight.tsx
  next/components/atoms/MImage.tsx
  next/components/atoms/Pagination/usePagination.ts
  next/components/atoms/QuantitySelect.tsx
  next/components/atoms/Seo.tsx
  next/components/molecules/ImageGallery.tsx
  next/components/molecules/Navigation/NavigationMenuMobile.tsx
  next/components/sections/Application/ApplicationStep4.tsx
  next/next-env.d.ts
  next/next.config.js
  next/package.json
  next/pages/bundles/[...fullPath].tsx
  next/pages/styleguide/index.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  next/public/pdf.worker.min.js
  next/public/pdf.worker.min.mjs
  next/utils/prefetchSections.ts
  next/yarn.lock
  strapi/package.json
  strapi/schema.graphql
Labels: pr: fix & ship :ship:

#436 Remove PDFViewer and related files
  next/components/atoms/PDFModalViewer.tsx
  next/components/atoms/PDFViewer.tsx
  next/components/layouts/DocumentLayout.tsx
  next/package.json
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  next/public/pdf.worker.min.mjs
  next/yarn.lock
Labels: pr: fix & ship :ship:

#431 #385 Disable custom image loader
  next/components/atoms/MImage.tsx
  next/components/atoms/RichText.tsx
  next/components/sections/HomepageSlider.tsx
Labels: pr: fix & ship :ship:

#437 #437 Maintenance: Pin yarn version to the repository
  next/package.json
  strapi/package.json
Labels: pr: fix & ship :ship:

#439 Fix: Remove `placeholder` and `blurDataURL` props from MImage
  next/components/atoms/MImage.tsx
  next/graphql/index.ts
  next/pages/styleguide/index.tsx
Labels: pr: fix & ship :ship:

#422 #419 Upgrade to Strapi 4.11.4 and fix Typescript in ceremonies-debtor-list…
  next/next-env.d.ts
  strapi/database/migrations/2023.06.14T00.00.00.update-file-paths.js
  strapi/package.json
  strapi/patches/@strapi+admin+4.11.4.patch
  strapi/patches/@strapi+plugin-content-manager+4.11.4.patch
  strapi/src/api/application/services/application.ts
  strapi/src/plugins/ceremonies-debtor-list/admin/src/pages/ImportSection.tsx
  strapi/src/plugins/ceremonies-debtor-list/package.json
  strapi/src/plugins/ceremonies-debtor-list/tsconfig.json
  strapi/src/plugins/ceremonies-debtor-list/yarn.lock
  strapi/yarn.lock
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#440 Setup email provider mailgun
  strapi/.env.example
  strapi/config/plugins.ts
  strapi/config/server.ts
  strapi/kubernetes/base/.env
  strapi/kubernetes/envs/Dev/.env
  strapi/kubernetes/envs/Prod/.env
  strapi/kubernetes/envs/Staging/.env
  strapi/package.json
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#452 #388 Map of objects in administration - groundwork
  next/components/molecules/Navigation/NavigationProvider/useGetFullPath.ts
  next/graphql/index.ts
  next/graphql/queries/components.gql
  next/graphql/queries/entities.gql
  next/graphql/queries/queries.gql
  next/next.config.js
  next/package.json
  next/services/fetchers/managedObjectsFetcher.ts
  strapi/schema.graphql
  strapi/src/api/managed-object/content-types/managed-object/schema.json
  strapi/src/api/managed-object/controllers/managed-object.ts
  strapi/src/api/managed-object/routes/managed-object.ts
  strapi/src/api/managed-object/services/managed-object.ts
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/map-of-managed-objects.json
Labels: pr: fix & ship :ship:

#468 Remove custom image loader
  next/components/atoms/MImage.tsx
  next/components/atoms/RichText.tsx
  next/components/sections/HomepageSlider.tsx
Labels: pr: fix & ship :ship:

#457 #448 upgrade plugin ceremonies debtor list
  strapi/package.json
  strapi/src/plugins/ceremonies-debtor-list/.nvmrc
  strapi/src/plugins/ceremonies-debtor-list/README.md
  strapi/src/plugins/ceremonies-debtor-list/admin/src/components/ImportSection.tsx
  strapi/src/plugins/ceremonies-debtor-list/admin/src/components/Initializer/index.tsx
  strapi/src/plugins/ceremonies-debtor-list/admin/src/components/PluginIcon/index.tsx
  strapi/src/plugins/ceremonies-debtor-list/admin/src/index.tsx
  strapi/src/plugins/ceremonies-debtor-list/admin/src/pages/App/index.tsx
  strapi/src/plugins/ceremonies-debtor-list/admin/src/pages/HomePage/index.tsx
  strapi/src/plugins/ceremonies-debtor-list/admin/src/pluginId.ts
  strapi/src/plugins/ceremonies-debtor-list/admin/src/utils/axiosInstance.ts
  strapi/src/plugins/ceremonies-debtor-list/custom.d.ts
  strapi/src/plugins/ceremonies-debtor-list/package.json
  strapi/src/plugins/ceremonies-debtor-list/remove-ceremonies-cron-task.ts
  strapi/src/plugins/ceremonies-debtor-list/server/bootstrap.ts
  strapi/src/plugins/ceremonies-debtor-list/server/content-types/index.ts
  strapi/src/plugins/ceremonies-debtor-list/server/controllers/index.ts
  strapi/src/plugins/ceremonies-debtor-list/server/destroy.ts
  strapi/src/plugins/ceremonies-debtor-list/server/index.ts
  strapi/src/plugins/ceremonies-debtor-list/server/register.ts
  strapi/src/plugins/ceremonies-debtor-list/server/routes/index.ts
  strapi/src/plugins/ceremonies-debtor-list/server/services/index.ts
  strapi/src/plugins/ceremonies-debtor-list/server/services/my-service.ts
  strapi/src/plugins/ceremonies-debtor-list/strapi-admin.js
  strapi/src/plugins/ceremonies-debtor-list/strapi-server.js
  strapi/src/plugins/ceremonies-debtor-list/tsconfig.json
  strapi/src/plugins/ceremonies-debtor-list/tsconfig.server.json
  strapi/src/plugins/ceremonies-debtor-list/yarn.lock
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#470 Add scrollbar-hide to appropriate homepage components
  next/components/molecules/Section.tsx
  next/components/sections/ArticleGroup.tsx
  next/components/sections/HomepageProceduresSection.tsx
Labels: pr: fix & ship :ship:

#473 #378 Update text in SkipToContentButton
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
Labels: pr: fix & ship :ship:

#474 Cleanup unused code
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.example
  next/.eslintrc.js
  next/components/atoms/Avatar.tsx
  next/components/atoms/Cookies/CookieBanner.tsx
  next/components/atoms/Cookies/CookieConsent.tsx
  next/components/atoms/Cookies/CookieSettingsModal.tsx
  next/components/atoms/Forms/FormCheckbox.tsx
  next/components/atoms/Forms/FormErrorWrapper.tsx
  next/components/atoms/Forms/FormRadioGroup.tsx
  next/components/atoms/Forms/FormTextField.tsx
  next/components/atoms/Pagination/usePagination.ts
  next/components/atoms/Radio/RadioBox.tsx
  next/components/atoms/Radio/RadioCircle.tsx
  next/components/atoms/Radio/RadioSimple.tsx
  next/components/atoms/Radio/RadioSimpleGroup.tsx
  next/components/atoms/ThirdPartyScripts.tsx
  next/components/atoms/Tooltip.tsx
  next/components/layouts/PageWrapper.tsx
  next/components/molecules/Cards/ArticleCard.tsx
  next/components/molecules/Cards/ProductCard.tsx
  next/components/molecules/Cards/ReviewCard.tsx
  next/components/molecules/Footer/Footer.tsx
  next/components/molecules/Footer/FooterMap.tsx
  next/components/molecules/Review.tsx
  next/components/molecules/ReviewsFiltering.tsx
  next/components/molecules/Row/Row.tsx
  next/components/sections/Application/ApplicationSection.tsx
  next/components/sections/Application/ApplicationSent.tsx
  next/components/sections/Application/ApplicationStep1.tsx
  next/components/sections/Application/ApplicationStep2.tsx
  next/components/sections/Application/ApplicationStep3.tsx
  next/components/sections/Application/ApplicationStep4.tsx
  next/components/sections/Application/ApplicationStep5.tsx
  next/components/sections/Application/ApplicationStep6.tsx
  next/components/sections/Application/ApplicationStep7.tsx
  next/components/sections/Application/ApplicationSummary.tsx
  next/components/sections/Application/application-shared.types.ts
  next/components/sections/Application/application-shared.yup.ts
  next/components/sections/Application/application.types.ts
  next/components/sections/Application/application.utils.ts
  next/components/sections/Application/useApplicationStep.tsx
  next/components/sections/Application/useSendApplication.ts
  next/graphql/index.ts
  next/graphql/queries/entities.gql
  next/graphql/queries/queries.gql
  next/pages/_app.tsx
  next/pages/application/consents.tsx
  next/pages/application/index.tsx
  next/pages/bundles/[...fullPath].tsx
  next/pages/styleguide.tsx
  next/services/fetchers/managedObjectsFetcher.ts
  strapi/schema.graphql
  strapi/src/api/application-text/content-types/application-text/schema.json
  strapi/src/api/application-text/controllers/application-text.ts
  strapi/src/api/application-text/routes/application-text.ts
  strapi/src/api/application-text/services/application-text.ts
  strapi/src/api/cemetery/content-types/cemetery/schema.json
Labels: pr: fix & ship :ship:

#479 #478 remove husky and lint-staged
  next/package.json
Labels: pr: fix & ship :ship:

#459 #420 upgrade strapi to 4.14.0
  .github/workflows/build.yml
  strapi/package.json
  strapi/patches/@strapi+admin+4.11.4.patch
  strapi/patches/@strapi+admin+4.14.0.patch
  strapi/patches/@strapi+plugin-content-manager+4.14.0.patch
  strapi/schema.graphql
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#475 #424 upgrade strapi to v4.15.5
  README.md
  strapi/.gitignore
  strapi/README.md
  strapi/config/middlewares.ts
  strapi/package.json
  strapi/patches/@strapi+admin+4.14.0.patch
  strapi/patches/@strapi+admin+4.15.5.patch
  strapi/patches/@strapi+plugin-content-manager+4.15.5.patch
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#480 #387 Remove legacy public-disclosure-section
  next/components/molecules/DisclosureIframe.tsx
  next/graphql/index.ts
  next/graphql/queries/entities.gql
  next/pages/pages/[...fullPath].tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/public-disclosure-section.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#485 Upgrade strapi to 4.25.20 and update patches
  strapi/README.md
  strapi/package.json
  strapi/patches/@strapi+admin+4.15.5.patch
  strapi/patches/@strapi+admin+4.25.20.patch
  strapi/patches/@strapi+plugin-content-manager+4.15.5.patch
  strapi/patches/@strapi+plugin-content-manager+4.25.20.patch
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#487 #426 Update robots file
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.example
  next/next.config.js
  next/pages/api/robots.ts
Labels: pr: fix & ship :ship:

#483 #482 Remove unused EN locale from Next and Strapi
  next/graphql/index.ts
  next/next-i18next.config.js
  next/package.json
  next/pages/_app.tsx
  next/public/locales/en/common.json
  next/yarn.lock
  strapi/README.md
  strapi/schema.graphql
  strapi/src/index.ts
Labels: pr: fix & ship :ship:

#490 Update revalidate secret
  next/kubernetes/base/secrets/general.secret.dev.yml
  next/kubernetes/base/secrets/general.secret.prod.yml
  next/kubernetes/base/secrets/general.secret.staging.yml
Labels: pr: fix & ship :ship:

#491 #488 Update managedObjects path
  next/components/molecules/Navigation/NavigationProvider/useGetFullPath.ts
Labels: pr: fix & ship :ship:
